## 实例描述
### 通过手动生成一个4*4的矩阵来模拟图片，定义一个2*2的滤波器，通过几个在卷积神经网络中常用的池化操作来测试池化函数里的参数，并验证输出结果

## 1.定义输入变量

In [1]:
# 定义1个输入变量模拟图片、4*4的2通道矩阵，并赋予指定值。
# 两个通道分别为4个0到3 3 3 3组成的矩阵， 4个4到7 7 7 7组成的矩阵
import tensorflow as tf
img = tf.constant([
        [[0.0, 4.0], [0.0, 4.0], [0.0, 4.0], [0.0, 4.0]],
        [[1.0, 5.0], [1.0, 5.0], [1.0, 5.0], [1.0, 5.0]],
        [[2.0, 6.0], [2.0, 6.0], [2.0, 6.0], [2.0, 6.0]],
        [[3.0, 7.0], [3.0, 7.0], [3.0, 7.0], [3.0, 7.0]]
    ])
img = tf.reshape(img, [1, 4, 4, 2])

## 2.定义池化操作

In [4]:
pooling = tf.nn.max_pool(img, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
pooling1 = tf.nn.max_pool(img, [1, 2, 2, 1], [1, 1, 1, 1], padding='VALID')
pooling2 = tf.nn.avg_pool(img, [1, 4, 4, 1], [1, 1, 1, 1], padding='SAME')
pooling3 = tf.nn.avg_pool(img, [1, 4, 4, 1], [1, 4, 4, 1], padding='SAME')
# tf.transpose:转置“a”。根据“perm”调整尺寸。
nt_hpool2_flat = tf.reshape(tf.transpose(img), [-1, 16])
pooling4 = tf.reduce_mean(nt_hpool2_flat, 1)  # 1表示对行求均值（1表示轴是列），0表示对列求均值

## 3.运行池化操作

In [8]:
with tf.Session() as sess:
    print("image:")
    image = sess.run(img)
    print(image)
    
    result = sess.run(pooling)
    print("result:\n", result)
    
    
    result1 = sess.run(pooling1)
    print("result1:\n", result1)
    
    result2 = sess.run(pooling2)
    print("result2:\n", result2)
    
    result3 = sess.run(pooling3)
    print("result3:\n", result3)
    
    flat,result4 = sess.run([nt_hpool2_flat, pooling4])
    print("result4:\n", result4)
    print("flat:\n", flat)

image:
[[[[0. 4.]
   [0. 4.]
   [0. 4.]
   [0. 4.]]

  [[1. 5.]
   [1. 5.]
   [1. 5.]
   [1. 5.]]

  [[2. 6.]
   [2. 6.]
   [2. 6.]
   [2. 6.]]

  [[3. 7.]
   [3. 7.]
   [3. 7.]
   [3. 7.]]]]
result:
 [[[[1. 5.]
   [1. 5.]]

  [[3. 7.]
   [3. 7.]]]]
result1:
 [[[[1. 5.]
   [1. 5.]
   [1. 5.]]

  [[2. 6.]
   [2. 6.]
   [2. 6.]]

  [[3. 7.]
   [3. 7.]
   [3. 7.]]]]
result2:
 [[[[1.  5. ]
   [1.  5. ]
   [1.  5. ]
   [1.  5. ]]

  [[1.5 5.5]
   [1.5 5.5]
   [1.5 5.5]
   [1.5 5.5]]

  [[2.  6. ]
   [2.  6. ]
   [2.  6. ]
   [2.  6. ]]

  [[2.5 6.5]
   [2.5 6.5]
   [2.5 6.5]
   [2.5 6.5]]]]
result3:
 [[[[1.5 5.5]]]]
result4:
 [1.5 5.5]
flat:
 [[0. 1. 2. 3. 0. 1. 2. 3. 0. 1. 2. 3. 0. 1. 2. 3.]
 [4. 5. 6. 7. 4. 5. 6. 7. 4. 5. 6. 7. 4. 5. 6. 7.]]


In [12]:
print(flat.shape)

(2, 16)
